apiVersion: v1
kind: Service
metadata:
  name: wordsmith-web-svc
  labels:
    app: wordsmith-web-svc
    environment: wordsmith-test-env
spec:
  ports:
    - port: 9191
      targetPort: 80
      name: wswebport
  selector:
    app: wordsmith-web-label
  type: LoadBalancer